### ISSUE TITLE
Comments on initial repo

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/ferc-xbrl-extractor#1]
# Data Acquisition / Inputs
* We need to archive the raw XBRL so that we can access the input files programmatically in the same way we access all the other data.
* Recent years of XBRL data are split into multiple zip archives for what seems like no good reason. Should we combine them into a single ZIP for archiving purposes?
* The names of the individual files making up the filings contain the old FERC Form 1 Respondent ID -- it's the number that follows the CamelCaseRespondentName in the file names. E.g. PSCo has `respondent_id==145`: `PublicServiceCompanyOfColorado-145-2020Q1F1.xbrl`
* Where are the taxonomies downloaded from? I don't see any URLs stored in the repo. A concrete example should be in the README. When I go try and find a taxonomy to download, the zipfile I get doesn't contain the file that's in the URL in the `extract_fuel` notebook. Where did you find that URL?
* Can we programmatically download the taxonomies for each year? How much do they change over time? What's the pattern for the URL downloading them? Is there a different taxonomy for every quarter? Every year? Do they revise the taxonomies in retrospect? Are old versions available? Do we need to archive the taxonomies that pertain to a given downloaded version of the data? (yes, probably yes). Do we need to use a separate taxonomy to process every single quarter/year of data? What do we need to do to ensure that all of the different years of data can coexist in the same database schema?
* It seems odd that the 2011 XBRL Zipfile file is only 29MB, while the 2020 zipfiles add up to 122MB. Why such a big difference?

# `xbrl_extract` CLI
* What happens if I don't give it a `--to-sql` argument? That's optional but... where does the data go if I don't give it that? The help message gives no indication.
* The script needs to provide logging output. When I run it nothing happens. Is it downloading the taxonomy? Is it converting data? Is there a problem? There are only like 400 filings per year, so it can print a line out for each one and be fine.
* Eventually it does start printing some output, but it appears to be going through the filings in a random order. Alphabetizing them would be good, so that adjacent records in the DB are related to each other, and also so that we can see roughly how far through the whole process we've gotten.
* Timestamps, loglevel, and other logging metadata should be output. I can't tell if these are logs or just `print()` statements, or how long the whole thing is taking.
* The output that's being generated is just paths to files. It doesn't say what is being done. I note that no SQLite DB is being created in the location that I specified. Is it going to read everything into memory before writing it out? The raw inputs for 2020 take 1.2 GB on disk, that could be a lot of memory.
* It seems to be maxing out one CPU, but not writing anything to disk. Can the reading of the individual filings be easily parallelized?
* For me it took 24 minutes to run through the 2020 data, and the resulting database is only 55MB which is crazy small compared to the 1.2 GB of the original data on disk.

# `extract_fuel.ipynb`
* The old database tables all start with `f1_` not `ferc_`  The PUDL FERC 1 database tables all end with `_ferc1` -- because we have a bunch of different FERC datasets, it's important never to name anything just "ferc" -- it always needs to have the form number.
* It's unclear to me how you're inferring the row numbers in the fuel table.  Are you literally just counting up the number of rows? Where did you get the magic number of 15 rows per supplement from?
* We should be able to do something simpler involving a function of `df.groupby("respondent_id").cumcount()` to assign the row and supplement numbers I think.
* I'm concerned that this method of assigning row numbers may fail catastrophically on some tables though. E.g. in the Plant In Service table, there are many header rows which take up row numbers, but do not contain data. Will those rows show up at all in the new data?
* The `FuelBurnedAverageHeatContent` column looks totally jacked. But I guess that's because we haven't cleaned up all the units errors yet.
* What's up with the `-0` and `-1` etc. suffixes in the `plant_name` column?

# `extract_steam.ipynb`
* Using column ordering to map old and new column names seems extremely fragile.
* The way the new and old columns are named is extremely different. I'm skeptical that this can be automated / generalized. On the upside, the new column names are much more informative.

# Row Numbers / DB structural differences.
* There are 183 tables in the new DB (vs 116 in the old one)
* There are 3679 columns in the new DB (vs about 3300 in the old one), but I think ~HALF of the columns in the old DB are `_f` footnote columns that don't contain real data, and I don't think any such columns exist in the new DB.
* Overall the 2020 data contains 558,580 records
* Clearly there are substantial structural differences between these two databases.
* Given that the new DB seems to have no concept of row numbers, one major issue is going to be mapping old records to the new records.  In the old DB there are ~3 different kinds of tables:
  * Tables where each record really does correspond to a single database record (e.g. `f1_fuel` or `f1_steam`)
  * Tables where individual rows have different semantic meanings, and those meanings potentially change over time as new rows are added. (e.g. the `f1_plant_in_srvce` table, where each row is a header, subtotal, total, or a particular FERC Account number).
  * Free form tables where row numbers are meaningless, and the respondents can enter whatever they want in one or more of the columns (e.g. the `f1_edcfu` / depreciation tables).
* Looking at the Plant in Service table in the new DB, it appears that they have turned those crazy rows number based contents into columns which is sensible. That table now has **485 columns** with long descriptive names (none of which include the FERC Account number of course!)
* These structures are going to be challenging to reconcile with each other in an automated way.
* Having 10 years of overlapping data that should be identical, reported in the two different formats, does open some potential ML based approaches...
* I think we may end up having two entirely separate sources of FERC1 data, which have to be managed separately, with different transformations that lead to a single consolidated / cleaned output in the PUDL DB.
* Looking at the modern version of `f1_edcfu_epda` (a messy depreciation table) the junk column where they list the FERC Acct. number (or a descriptive string) still seems to be a total mess. However there's a couple of columns that look like they're supposed to somehow indicate the order in which these rows should appear, and potentially provide some additional information about how they are grouped.

**Comment by zschira** [comment]
# Data Acquisition / Inputs

> We need to archive the raw XBRL so that we can access the input files programmatically in the same way we access all the other data.

New XBRL filings are distributed via an RSS feed, and I'm working on a basic implementation to pull these filings. We will need to decide where this code will live/how it will integrate with `pudl-scrapers`, as `scrapy` is not necessary to get content from an RSS feed.

> Recent years of XBRL data are split into multiple zip archives for what seems like no good reason. Should we combine them into a single ZIP for archiving purposes?

We can certainly store all flings pulled from the RSS feed in a single zip file. I suppose we'll need to decide generally what we're going to do with the overlapping years.

> The names of the individual files making up the filings contain the old FERC Form 1 Respondent ID -- it's the number that follows the CamelCaseRespondentName in the file names. E.g. PSCo has respondent_id==145: PublicServiceCompanyOfColorado-145-2020Q1F1.xbrl

Ah, good to know. Unfortunately I don't think this is true of the data distributed via their RSS feed. The filenames from here look like this: `wk-20211231.xml`

> - Where are the taxonomies downloaded from? I don't see any URLs stored in the repo. A concrete example should be in the README. When I go try and find a taxonomy to download, the zipfile I get doesn't contain the file that's in the URL in the extract_fuel notebook. Where did you find that URL?
> - Can we programmatically download the taxonomies for each year? How much do they change over time? What's the pattern for the URL downloading them? Is there a different taxonomy for every quarter? Every year? Do they revise the taxonomies in retrospect? Are old versions available? Do we need to archive the taxonomies that pertain to a given downloaded version of the data? (yes, probably yes). Do we need to use a separate taxonomy to process every single quarter/year of data? What do we need to do to ensure that all of the different years of data can coexist in the same database schema?

A url to the taxonomy used for an individual filing is actually included in the filing, so we should really just get the taxonomy automatically from that URL. I've created an issue to change this #2. It's a pretty simple change, so I'll get that done soon.

> It seems odd that the 2011 XBRL Zipfile file is only 29MB, while the 2020 zipfiles add up to 122MB. Why such a big difference?

Yeah I'm not sure what the deal is here, definitely needs further looking in to. I did email Robert Hudson at FERC and regarding the converted data he said:

>These XBRL instance files are not perfect, we are still finding mistakes in our conversion, and we did miss some filings, but it is the best we can do for now.

So, as with much of this process, I'm not sure if there's a simple answer.

# xbrl_extract CLI
> What happens if I don't give it a --to-sql argument? That's optional but... where does the data go if I don't give it that? The help message gives no indication.

Yeah I did that when I wasn't really sure what the CLI was going to look like, or if there would be options to convert to another format, but I'll just go ahead and make this a required argument.

> - The script needs to provide logging output. When I run it nothing happens. Is it downloading the taxonomy? Is it converting data? Is there a problem? There are only like 400 filings per year, so it can print a line out for each one and be fine.
> - Eventually it does start printing some output, but it appears to be going through the filings in a random order. Alphabetizing them would be good, so that adjacent records in the DB are related to each other, and also so that we can see roughly how far through the whole process we've gotten.
> - Timestamps, loglevel, and other logging metadata should be output. I can't tell if these are logs or just print() statements, or how long the whole thing is taking.

Yeah I've been trying to push hard with functionality, I need to go back and add logging, improve the cli, clean things up, add more comments etc. I added an issue for logging specifically #3.

> - The output that's being generated is just paths to files. It doesn't say what is being done. I note that no SQLite DB is being created in the location that I specified. Is it going to read everything into memory before writing it out? The raw inputs for 2020 take 1.2 GB on disk, that could be a lot of memory.
> - It seems to be maxing out one CPU, but not writing anything to disk. Can the reading of the individual filings be easily parallelized?

In an early implementation I was running into a bottle neck when writing to disk after each filing, so I decided to do it all in memory first, then write the whole thing to disk. I'll probably start by just adding a `batch_size` option and processing filings in batches to avoid writes after every single filing. As for parallelization, this should be quite straightforward. Every filing stands on its own and is a unique file on disk, so likely the hardest part will just be synchronizing writes to the SQLite DB. Processing in batches will also work well with parallel processing.

> For me it took 24 minutes to run through the 2020 data, and the resulting database is only 55MB which is crazy small compared to the 1.2 GB of the original data on disk.

XBRL instances are very large, so the size difference is not necessarily surprising to me. We do want a way to robustly verify that no data is being lost in the extraction, but I'm not exactly sure how to do that given that FERC is not confident in their own conversion.

**Comment by zaneselvans** [comment]
I don't know that we really want to be pulling one filing at a time from the RSS feed as they're released. Is there a date by which the entire quarter's worth of filings are finalized? Are they going to be publishing archives that contain the entirety of each quarter's or year's worth of filing?

**Comment by zschira** [comment]
I haven't seen anything indicating a specific date when all filings will be finalized, or that they will be publishing archives of an entire quarter's worth of data. I'll try to get some more solid answers on those questions, but my inclination is that they are relying on the RSS feed and their [eForms Portal](https://ecollection.ferc.gov/submissionHistory) for distribution.

**Comment by zaneselvans** [comment]
Looking through the modules now:

# General Comments
* The code is concise and broken down into small, relatively simple chunks, which is great.
* However, there's not enough context in the comments / docstrings explaining the why behind what you're doing, or the context of the objects / data structures which you're working with, so it's hard to understand what's going on, even though the code itself is clear.
* Let's get a `dev` branch going so that we can use GitHub's PR infrastructure for review and conversation, inline with the code.
* I'd also like to set up some linting / CI stuff.

# `cli.py`
* I think `args.to_sql` needs to be updated to `sql_path`
* Can we give the keyword args explicitly in functions like `xbrl.extract` which have lots of arguments? For clarity and to avoid issues from the order changing somehow?

# `xbrl.py`
* Is `loglevel` really a `bool`?
* Add return type hints?
* Does using `ThreadPoolExecutor` speed things up? Is the process I/O bound? I had to use `ProcessPoolExecutor` for the EPA CEMS. I should do that same thing with the `partial()` function over there rather than replicating all the invariate inputs.
* The class is `Executor` but the instance in the context manager is called `executer` (e swapped for o)
* Is it faster / less memory intensive to do one concatenation of all the dataframes at once, rather than repeatedly concatenating one more onto the existing dataframe? Like build up a list of dataframes, and then run `pd.concat()` on the whole thing.
* What role does the `filing_id` that's being generated play? Is it likely to change across runs as the number or ordering of filings changes? Inconstant IDs often get us into trouble because people hard-code thing, imagining that they are permanent like the EIA Plant IDs, or the FERC respondent IDs.
* Can you explain more what is happening in `get_cols_from_line_item()`? It looks like some kind of recursive thing bouncing back and forth to `get_columns_from_table()`? In the end is it going to return a dictionary of dtypes?
* Let's use either `cols` or `columns` in the function names but not switch back and forth for consistency.

# `taxonomy.py`
* What's a `LinkRole`? What's a `Concept`? Why are the first few elements of a `Concept` or `LinkRole` special?
* What's going on in `Taxonomy.get_page()` What is `section` and why the `zfill(3)`?
* Need more than 1 line of context explaining the structures that are being manipulated.
* What kind of info is potentially getting output to the metadata file by `save_references()`? Why is this useful / interesting?

**Comment by zaneselvans** [comment]
Obsolete
