### ISSUE TITLE
tox-pytest badge always says "failing"

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/ferc-xbrl-extractor#159]
Even when our tests are passing, the badge in the README says it's failing. I don't get it. [Instructions for workflow status badges](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge).

This is the address for the badge:
https://github.com/catalyst-cooperative/ferc-xbrl-extractor/workflows/tox-pytest/badge.svg

And here's what it looks like as of 2023-10-18T19:55
![tox-pytest](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/workflows/tox-pytest/badge.svg)

But it's [all green in the actions](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/actions/workflows/tox-pytest.yml):

![image](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/assets/596279/9b29d5a5-cd90-4be2-9940-24ca902f2da2)

**Comment by e-belfer** [comment]
The link is wrong! It should be:
https://github.com/catalyst-cooperative/ferc-xbrl-extractor/actions/workflows/tox-pytest.yml/badge.svg
Instead it is currently:
https://github.com/catalyst-cooperative/ferc-xbrl-extractor/workflows/tox-pytest/badge.svg

Will fix!
