### ISSUE TITLE
FERC XBRL taxonomy parsing occasionally hangs for 10+ minutes

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/ferc-xbrl-extractor#32]
Occasionally, when extracting the FERC XBRL data in the Taxonomy parsing step, the process will hang for a very long time. I've seen it take 15 minutes and then resume normal operation (and I've also quit out of it after 20 minutes).  Normally this process takes only a few seconds.

It seems to be totally stochastic.  Like if you run the extraction over and over and over again at the command line, it'll be fine 90% of the time and then once in a while it gets stuck. It seems like it can happen on any of the FERC forms. Very odd.

Not sure if it's related at all, but I sometimes also get this failed assertion when it's hanging. Not sure why it would only appear *sometimes*

```
dyld[70238]: Assertion failed: (this->magic == kMagic), function matchesPath, file Loader.cpp, line 154.
```

**Comment by jdangerx** [comment]
I haven't seen this happen in a while... @zaneselvans have you?

**Comment by zaneselvans** [comment]
No, I haven't seen this in ages.

**Comment by zaneselvans** [comment]
With all the changes that have happened for the extractor, and the fact that this hasn't come up in a long time, I'm going to close this.
